# Generated by Django 3.0.4 on 2020-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(max_length=100)),
                ('genre2', models.CharField(blank=True, max_length=100)),
                ('plan', models.CharField(max_length=500)),
                ('urllink', models.CharField(blank=True, max_length=2000)),
                ('tag1', models.CharField(blank=True, max_length=100)),
                ('tag2', models.CharField(blank=True, max_length=100)),
                ('tag3', models.CharField(blank=True, max_length=100)),
                ('done', models.BooleanField()),
                ('review', models.IntegerField(blank=True)),
                ('motivation', models.IntegerField(blank=True)),
                ('travelhour', models.IntegerField(blank=True)),
                ('travelmin', models.IntegerField(blank=True)),
                ('completiondate', models.DateField(blank=True)),
            ],
        ),
    ]
