# Generated by Django 3.0.4 on 2020-04-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatePlan',
            new_name='WannaDo',
        ),
    ]
