# Generated by Django 3.0.4 on 2020-04-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0002_auto_20200414_0946'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wannado',
            table='forpis_wannado',
        ),
    ]
