# Generated by Django 3.0.4 on 2020-04-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0003_auto_20200414_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='WannaDo_motivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.IntegerField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')])),
            ],
        ),
    ]
