# Generated by Django 3.0.4 on 2020-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0004_wannado_motivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressStressrelief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(max_length=100)),
                ('genre2', models.CharField(blank=True, max_length=100)),
                ('plan', models.TextField()),
                ('urllink', models.TextField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('done', models.BooleanField()),
                ('review', models.IntegerField(blank=True)),
                ('motivation', models.IntegerField(blank=True)),
                ('completiondate', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'forpis_progress_stressrelief;',
            },
        ),
        migrations.CreateModel(
            name='WannaDo_genre1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(choices=[('習慣', '習慣'), ('勉強', '勉強'), ('本', '本'), ('アプリ', 'アプリ'), ('家事', '家事'), ('ストレス解消', 'ストレス解消'), ('趣味', '趣味'), ('コロナ後', 'コロナ後'), ('成功後', '成功後')], max_length=100)),
            ],
        ),
    ]
