# Generated by Django 3.0.4 on 2020-04-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0005_progressstressrelief_wannado_genre1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='progressstressrelief',
            table='forpis_progress_stressrelief',
        ),
    ]
