# Generated by Django 3.0.4 on 2020-05-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0006_auto_20200430_2010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='progressstressrelief',
            table='stressrelief',
        ),
        migrations.AlterModelTable(
            name='wannado',
            table='wannado',
        ),
    ]
