# Generated by Django 3.0.4 on 2020-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0007_auto_20200501_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wannado_genre1',
            name='genre1',
            field=models.CharField(choices=[('習慣', '習慣'), ('勉強', '勉強'), ('本', '本'), ('アプリ', 'アプリ'), ('家事', '家事'), ('趣味', '趣味'), ('コロナ後', 'コロナ後'), ('成功後', '成功後')], max_length=100),
        ),
    ]
