# Generated by Django 3.0.4 on 2020-05-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0009_progresshabit_progresshabit_motivation_progressstressrelief_motivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressHabit_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(blank=True, choices=[('やめたい', '0'), ('毎日', '1'), ('毎週', '2'), ('毎週', '3')])),
            ],
        ),
    ]
