# Generated by Django 3.0.4 on 2020-05-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0010_progresshabit_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressHabit_division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField(blank=True, choices=[('0', 'ー'), ('1', '朝'), ('2', '昼'), ('3', '夜'), ('4', '月'), ('5', '火'), ('6', '水'), ('7', '木'), ('8', '金')])),
            ],
        ),
        migrations.AlterField(
            model_name='progresshabit_frequency',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[('0', 'やめたい'), ('1', '毎日'), ('2', '毎週'), ('3', '毎週')]),
        ),
    ]
