# Generated by Django 3.0.4 on 2020-05-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0011_auto_20200503_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresshabit_division',
            name='division',
            field=models.CharField(blank=True, choices=[('朝', '朝'), ('昼', '昼'), ('夜', '夜'), ('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金')], max_length=100),
        ),
    ]
