# Generated by Django 3.0.4 on 2020-05-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0012_auto_20200504_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresshabit',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
