# Generated by Django 3.0.4 on 2020-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0013_auto_20200504_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresshabit',
            name='division',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='progresshabit',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
