# Generated by Django 3.0.4 on 2020-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0014_auto_20200504_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresshabit_frequency',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[('0', 'やめたい'), ('1', '毎日'), ('2', '毎週'), ('3', '毎月')]),
        ),
    ]
