# Generated by Django 3.0.4 on 2020-05-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0017_auto_20200505_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgressHabit',
            new_name='Habit',
        ),
        migrations.RenameModel(
            old_name='ProgressHabit_division',
            new_name='Habit_division',
        ),
        migrations.RenameModel(
            old_name='ProgressHabit_frequency',
            new_name='Habit_frequency',
        ),
        migrations.RenameModel(
            old_name='ProgressHabit_motivation',
            new_name='Habit_motivation',
        ),
        migrations.RenameModel(
            old_name='ProgressStressrelief',
            new_name='Relief',
        ),
        migrations.RenameModel(
            old_name='ProgressStressrelief_motivation',
            new_name='Relief_motivation',
        ),
        migrations.AlterModelTable(
            name='relief',
            table='relief',
        ),
    ]
