# Generated by Django 3.0.4 on 2020-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0018_auto_20200510_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='WannaDo_genre2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre2', models.CharField(blank=True, choices=[('目標', '目標'), ('お金', 'お金'), ('IT', 'IT'), ('資格', '資格'), ('動画', '動画'), ('語学', '語学'), ('時事', '時事'), ('考え整理', '考え整理'), ('啓発', '啓発'), ('マンガ', 'マンガ'), ('動画', '動画'), ('youtube', 'youtube'), ('netflix', 'netflix'), ('欲しい', '欲しい'), ('美容', '美容'), ('他', '他')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='wannado_genre1',
            name='genre1',
            field=models.CharField(choices=[('勉強', '勉強'), ('本', '本'), ('趣味', '趣味'), ('コロナ後', 'コロナ後'), ('他', '他')], max_length=100),
        ),
    ]
