# Generated by Django 3.0.4 on 2020-05-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0019_auto_20200511_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit_genre1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(choices=[('意思', '意思'), ('行動', '行動'), ('向上', '向上'), ('喧嘩', '喧嘩'), ('目標', '目標'), ('関係', '関係'), ('他', '他')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='habit_division',
            name='division',
            field=models.CharField(blank=True, choices=[('朝', '朝'), ('昼', '昼'), ('夜', '夜'), ('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('土日', '土日')], max_length=100),
        ),
        migrations.AlterField(
            model_name='wannado_motivation',
            name='motivation',
            field=models.IntegerField(blank=True, choices=[('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')]),
        ),
    ]
