# Generated by Django 3.0.4 on 2020-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0020_auto_20200511_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='WannaDo_deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.IntegerField(blank=True, choices=[('0', 'コロナ後'), ('1', '今月'), ('2', '5~6月'), ('3', '7~9月'), ('4', '10~12月'), ('5', '今年'), ('6', '3年後'), ('7', '5年後'), ('8', 'いつか')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wannado',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
