# Generated by Django 3.0.4 on 2020-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0021_auto_20200521_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wannado_deadline',
            name='deadline',
            field=models.IntegerField(blank=True, choices=[('0', 'コロナ後'), ('1', '今月'), ('2', '5~6月'), ('3', '7~9月'), ('4', '10~12月'), ('5', '今年'), ('6', '3年以内'), ('7', '5年以内'), ('8', 'いつか')], null=True),
        ),
    ]
