# Generated by Django 3.0.4 on 2020-06-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0023_auto_20200524_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre1', models.CharField(blank=True, max_length=100)),
                ('plan', models.TextField(blank=True)),
                ('plandate', models.DateField(blank=True)),
                ('planurllink', models.TextField(blank=True)),
                ('planmemo', models.TextField(blank=True)),
                ('get', models.TextField(blank=True)),
                ('getdate', models.DateField(blank=True)),
                ('geturllink', models.TextField(blank=True)),
                ('getmemo', models.TextField(blank=True)),
                ('done', models.BooleanField()),
                ('review', models.IntegerField(blank=True)),
                ('motivation', models.IntegerField(blank=True)),
                ('completiondate', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'relate',
            },
        ),
        migrations.CreateModel(
            name='Relate_motivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.IntegerField(blank=True, choices=[('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')])),
            ],
        ),
    ]
