# Generated by Django 3.0.4 on 2020-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0026_auto_20200605_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate_thanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thanksgenre1', models.CharField(blank=True, max_length=100)),
                ('thanks', models.TextField(blank=True)),
                ('thanksdate', models.DateField(blank=True)),
                ('thanksurllink', models.TextField(blank=True)),
                ('thanksmemo', models.TextField(blank=True)),
                ('thanksreview', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'relate_thanks',
            },
        ),
        migrations.DeleteModel(
            name='Relate_get',
        ),
    ]
