# Generated by Django 3.0.4 on 2020-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0027_auto_20200605_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='genre1',
            new_name='habitgenre1',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='memo',
            new_name='habitmemo',
        ),
        migrations.RenameField(
            model_name='habit_genre1',
            old_name='genre1',
            new_name='habitgenre1',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='habitflag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='probgenre1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='habit',
            name='probgenre2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='habit',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='probmemo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='proburl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
