# Generated by Django 3.0.4 on 2020-06-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0028_auto_20200609_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habit_genre1',
            new_name='Habit_habitgenre1',
        ),
    ]
