# Generated by Django 3.0.4 on 2020-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0029_auto_20200609_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habitgenre1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='habit',
            name='motivation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
