# Generated by Django 3.0.4 on 2020-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0032_auto_20200609_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_frequency',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[('0', 'やめたい'), ('1', '毎日'), ('2', '毎週'), ('3', '毎月')], default='1'),
        ),
    ]
