# Generated by Django 3.0.4 on 2020-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0036_auto_20200609_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relate_motivation',
            name='motivation',
            field=models.IntegerField(blank=True, choices=[('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default=4),
        ),
    ]
