# Generated by Django 3.0.4 on 2020-06-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0037_auto_20200609_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='wannado',
            name='plandate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
