# Generated by Django 3.0.4 on 2020-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0039_auto_20200609_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_habitgenre1',
            name='habitgenre1',
            field=models.CharField(choices=[('意思', '意思'), ('行動', '行動'), ('向上', '向上'), ('喧嘩', '喧嘩'), ('目標', '目標'), ('関係', '関係'), ('他', '他')], default='意思', max_length=100),
        ),
    ]
