# Generated by Django 3.0.4 on 2020-06-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0040_auto_20200610_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit_probgenre1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probgenre1', models.CharField(blank=True, choices=[('生活', '生活'), ('心', '心')], default='心', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habit_probgenre2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probgenre2', models.CharField(blank=True, choices=[('怒り', '怒り'), ('イライラ', 'イライラ'), ('ネガティブ', 'ネガティブ'), ('不安', '不安'), ('人生最悪', '人生最悪'), ('やる気', 'やる気'), ('睡眠', '睡眠')], default='不安', max_length=100)),
            ],
        ),
    ]
