# Generated by Django 3.0.4 on 2020-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0041_habit_probgenre1_habit_probgenre2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_probgenre1',
            name='probgenre1',
            field=models.CharField(blank=True, choices=[('生活', '生活'), ('心', '心'), ('他', '他')], default='心', max_length=100),
        ),
        migrations.AlterField(
            model_name='habit_probgenre2',
            name='probgenre2',
            field=models.CharField(blank=True, choices=[('怒り', '怒り'), ('イライラ', 'イライラ'), ('ネガティブ', 'ネガティブ'), ('不安', '不安'), ('人生最悪', '人生最悪'), ('やる気', 'やる気'), ('睡眠', '睡眠'), ('他', '他')], default='不安', max_length=100),
        ),
    ]
