# Generated by Django 3.0.4 on 2020-06-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0042_auto_20200613_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_probgenre2',
            name='probgenre2',
            field=models.CharField(blank=True, choices=[('怒り', '怒り'), ('イライラ', 'イライラ'), ('ネガティブ', 'ネガティブ'), ('不調', '不調'), ('不安', '不安'), ('人生最悪', '人生最悪'), ('やる気', 'やる気'), ('睡眠', '睡眠'), ('他', '他')], default='不安', max_length=100),
        ),
    ]
