# Generated by Django 3.0.4 on 2020-06-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forpis', '0043_auto_20200617_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wannado_deadline',
            name='deadline',
            field=models.IntegerField(blank=True, choices=[('0', 'コロナ後'), ('1', '今月'), ('2', '5~6月'), ('3', '7~9月'), ('4', '10~12月'), ('5', '今年'), ('6', '3年以内'), ('7', '5年以内'), ('8', 'いつか')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='wannado_genre1',
            name='genre1',
            field=models.CharField(choices=[('勉強', '勉強'), ('本', '本'), ('趣味', '趣味'), ('コロナ後', 'コロナ後'), ('他', '他')], default='勉強', max_length=100),
        ),
        migrations.AlterField(
            model_name='wannado_motivation',
            name='motivation',
            field=models.IntegerField(blank=True, choices=[('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default=5),
        ),
    ]
